### ISSUE TITLE
allow for functions instead of just arrays of functions

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/metascraper#10]
I think it would be simple to do, and kind of nice to allow rules to be defined with just a single function, instead of always needing to be an array. Such that as simple case could look like...

```js
title: async (window) => window.document.title.textContent
```

Or the complex ones could be:

```js
title: [
  // tons of rules...
]
```

@blakeembrey that sound good to you?

**Comment by blakeembrey** [comment]
Makes sense. The single function could even just be a composed version of the array anyway. Probably not a big deal to do either behaviour - since having a single rule is just a matter of wrapping it in an array.

**Comment by ianstormtaylor** [comment]
Added in `0.2.0`!
