### ISSUE TITLE
ES6 syntax fails in node v4 and 5

### ISSUE THREAD

**Issue by nmehta6** [ianstormtaylor/metascraper#15]
I am really looking forward to trying this project out. My node version is v5.5.0. I am getting the following syntax error:

<img width="644" alt="screen shot 2016-07-08 at 3 30 06 pm" src="https://cloud.githubusercontent.com/assets/1521532/16700694/06d81d06-4521-11e6-8241-df50611bdf27.png">

I believe this is because the ES6 default parameters are not supported in my version of node.

**Comment by ianstormtaylor** [comment]
Ah shoot, good call. Published with this fixed in `1.0.4`, let me know if that works!
