### ISSUE TITLE
Unusable in Node 4

### ISSUE THREAD

**Issue by yongfei25** [ianstormtaylor/metascraper#18]
Hi,

It seem that the published npm packge isn't transpiled by Babel.

**Comment by yongfei25** [comment]
Unsupported feature like const, let, array destructuring, etc. I think babel is supposed to transpile them when publishing to npm.

**Comment by ianstormtaylor** [comment]
Sorry about that, forgot that `const` and array destructuring wasn't available. I just published `1.0.5` which should fix the problem!

**Comment by yongfei25** [comment]
Thanks!
