### ISSUE TITLE
SyntaxError while running under Node LTS (v4.x)

### ISSUE THREAD

**Issue by emanuelecasadio** [ianstormtaylor/metascraper#19]
When I try to `require('metascraper')` I got this error:

    /home/user/workspace/node_modules/metascraper/lib/index.js:2
    let RULES = require('./rules')
    ^^^
    
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

My suggestion is to add the `'use strict';` on top of each file containing a block-scoped declaration.

**Comment by ianstormtaylor** [comment]
Sorry about that. Just published `1.0.6` which is transpiled with Babel, so it should fix the issue! Let me know if you run into anything further.
