### ISSUE TITLE
XMLHttpRequest cannot load https://github.com/ianstormtaylor/metascraper/issues/27. No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by leeeejuy** [ianstormtaylor/metascraper#28]
XMLHttpRequest cannot load https://github.com/ianstormtaylor/metascraper/issues/27. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.lululala.co.kr:8000' is therefore not allowed access.

:8000/#/:1 Uncaught (in promise) 
PopsicleError {cause: undefined, code: "EUNAVAILABLE", popsicle: Request, message: "Unable to connect to "https://github.com/ianstormtaylor/metascraper/issues/27"", name: "PopsicleError"…}

how should i do???

**Comment by blakeembrey** [comment]
You should create a server-side proxy for this sort of activity. CORS is a regular protection to avoid vulnerabilities with browsers requesting across domains. You definitely will not be allowed to request someone's website who does not allow you via CORS headers.

**Comment by leeeejuy** [comment]
i want to external website meta data. so cors error... how should i do?? 
where is cors headers ???

**Comment by blakeembrey** [comment]
You can not make the requests from the browser, it's a browser protection. You need to write a server-side proxy, as I mentioned above, if you want to scrape arbitrary pages that you aren't on.

**Comment by mahnuh** [comment]
Closing this issue now, see my comment [here](https://github.com/ianstormtaylor/metascraper/issues/33#issuecomment-348753006) for reference.
