### ISSUE TITLE
CORS Issue... 

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [ianstormtaylor/metascraper#33]
i saw the https://github.com/ianstormtaylor/metascraper/issues/27 
i did you say that, but cors error...
error: XMLHttpRequest cannot load http://www.naver.com/. Redirect from 'http://www.naver.com/' to 'https://www.naver.com/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.lululala.co.kr:8000' is therefore not allowed access.

i'm a front-end developer.. so i must solve the cors in front...
please tell me... the solve
how can i do?
please.... help me.

**Comment by akapetzoglou** [comment]
Hey! Did you maybe find a way to approach this?

**Comment by mahnuh** [comment]
As pointed out in [this](https://github.com/ianstormtaylor/metascraper/issues/28#issuecomment-304704679) comment CORS is a protection in your browser. So to solve your issue you need to do some changes server-side.

See this explanation for reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

A really nice explanation and solution can be found here: https://blog.crashtest-security.com/multiple-values-access-control-allow-origin-3c7cafc8c5c0
