### ISSUE TITLE
add `tags` property

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/metascraper#4]
There are a few different metadata syntaxes out there for tags, would return an array of them. Maybe even join across syntaxes to get the full list. And then unique with case insensitivity

**Comment by Kikobeats** [comment]
Not sure what `tags` means. Can you provide any blog article about that?

**Comment by ianstormtaylor** [comment]
Ah yup, it's like #21. The "keywords", or some metadata call them "tags" I believe. But just keywords that might be associated with the content.

**Comment by ianstormtaylor** [comment]
Actually, `keywords` sounds like a better name for the, so closing in favor of #21
