### ISSUE TITLE
Strict author check would fail on non-ASCII names

### ISSUE THREAD

**Issue by blakeembrey** [ianstormtaylor/metascraper#5]
In https://github.com/ianstormtaylor/metascraper/blob/master/lib/rules/author.js. Maybe a better check is `/^\S+\s+\S+/`?

**Comment by ianstormtaylor** [comment]
Damn, yeah. Trouble for this specific one is that I was edging towards having fewer false positives, at the expense of throwing on some valid names. If we loosen it too much, it starts matching things with symbols in them, etc. Not sure if there's a good solution 😖

**Comment by ianstormtaylor** [comment]
Open to ideas though, or even completely different rules that come before it that make the later ones irrelevant!

**Comment by blakeembrey** [comment]
I don't mind on false positives as much. I'd prefer to get more rather than less data. That said, it could skip a few other characters. E.g. `/^[^\s$#@!&*]+\s+[^...]/`. The problem is, it's even perfectly legitimate to have some symbols such as "Dr. Who", "O'Farrell, James", etc. I think I'd err on the side of less strictness and use the non-whitespace, whitespace, non-whitespace until you have more data on this (unless you already do?)

**Comment by ianstormtaylor** [comment]
Sounds good to me, added a ton of new test cases and it only affected one, in a positive way! Added in `0.2.4`
