### ISSUE TITLE
Remove dependency on Babel?

### ISSUE THREAD

**Issue by blakeembrey** [ianstormtaylor/metascraper#7]
Currently the build actually relies on the end-user having Babel installed and all of Babel core. It'd be nicer on us users if we could use it without Babel.

**Comment by ianstormtaylor** [comment]
AH :$ this is totally just because I haven't released an ES6-using module before, so I didn't know how to bundle it without Babel. Definitely don't want to force that on people. I guess maybe the tests should be refactored to not use the nice syntax, so that we guarantee it's not a dependency

**Comment by ianstormtaylor** [comment]
Okay this should be fixed in `0.1.1`!

**Comment by ryanmcclure4** [comment]
It seems this package is now using async/await again...Is there a reason this is not bring transpiled for distribution?

**Comment by Kikobeats** [comment]
No more necessary, just upgrade your node version or use a old metascraper release version 🙂

**Comment by ryanmcclure4** [comment]
Wow, I had no idea it was released in node :P thanks!
