### ISSUE TITLE
Remove async/await

### ISSUE THREAD

**Issue by blakeembrey** [ianstormtaylor/metascraper#8]
It'd be nicer on users if it were written in ES5 promises. Related to https://github.com/ianstormtaylor/metascraper/issues/7. Current implementation relies on a regenerator runtime from Babel to support `async`/`await`.

**Comment by ianstormtaylor** [comment]
Fixed in `0.1.1`!

**Comment by blakeembrey** [comment]
Awesome, cheers 😄
