### ISSUE TITLE
Async rules?

### ISSUE THREAD

**Issue by blakeembrey** [ianstormtaylor/metascraper#9]
I noticed this uses async rules, any particular reason? Seems all the current rules are completely synchronous.

FWIW, if you just want to compose async functions I wrote https://github.com/blakeembrey/throwback. It takes a chain of functions that return promises and any can either `return value` or `return next()` to continue execution. Might be a nice middleware pattern here if you want to keep async middleware.

**Comment by ianstormtaylor** [comment]
Nice, `throwback` looks cool!

For async, I wasn't totally sure, but it seemed like keeping it async everywhere (url, html, window) made it nicely parallel, and didn't edge out use cases I hadn't thought of. 

For example, there was one thing I had considered doing which was grabbing `property="twitter:author:id"` meta tags and expanding them by querying the Twitter API to get the author's full name. In a far-down-the-stack fallback for cases where the author isn't surfaced at all. It seemed like keeping it async would allow those kinds of more complex scraping use cases where something actually need to be calculated from the scraped data, without the user having to manage that themselves afterward. But maybe that's too complex...

Definitely most simple scraping cases would be sync.

**Comment by ianstormtaylor** [comment]
Closing now since rules can either by sync or async by returning a promise!
